---

repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--strict]

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.1.2
    hooks:
      - id: ansible-lint

  - repo: local
    hooks:
      - id: packer-fmt
        name: packer fmt
        entry: packer fmt -check -diff -recursive .
        language: system
        pass_filenames: false
        files: \.pkr\.hcl$
