---
- name: Update System
  hosts: all
  become: true
  tasks:
    - name: Update Fedora system
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_distribution == "Fedora"

    - name: Update Debian/Ubuntu system
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Update RHEL/CentOS/AlmaLinux system
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
