---
- name: Setup RockyLinux for Vagrant
  hosts: all
  become: yes
  tasks:
    - name: Install additional packages for RockyLinux
      dnf:
        name:
          - vim
          - wget
          - curl
          - git
          - bash-completion
          - cloud-init
          - cloud-utils-growpart
          - NetworkManager
          - qemu-guest-agent
        state: present

    - name: Enable NetworkManager service
      systemd:
        name: NetworkManager
        enabled: yes

    - name: Enable qemu-guest-agent service
      systemd:
        name: qemu-guest-agent
        enabled: yes

    - name: Configure cloud-init for Vagrant
      copy:
        dest: /etc/cloud/cloud.cfg.d/90_vagrant.cfg
        content: |
          datasource_list: [ NoCloud, ConfigDrive, None ]
        mode: '0644'

    - name: Disable NetworkManager's DNS management
      copy:
        dest: /etc/NetworkManager/conf.d/90-dns-none.conf
        content: |
          [main]
          dns=none
        mode: '0644'
